version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=reviews
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=127.0.0.1
    ports:
      - "3306:3306"


      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=password

